// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'inner': string;
  'inputHelp': string;
  'login': string;
  'loginCard': string;
  'loginContent': string;
  'loginFooter': string;
  'logo': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
